version: '3'
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - techproducts
      - /opt/solr/server/solr/configsets/sample_techproducts_configs/conf
volumes:
  data:
