version: '3'
services:
  solr:
    # Used in project solr:7.3.1
    image: solr:6.3
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - techproducts
      - /opt/solr/server/solr/configsets/sample_techproducts_configs/conf
volumes:
  data:
