version: '3'
services:
  solr:
    # 書籍だと、Solrのバージョンは6.3
    image: solr:7.3.1
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - techproducts
      - /opt/solr/server/solr/configsets/sample_techproducts_configs/conf
volumes:
  data:
